"""change default time to utc

Revision ID: 041f91a5ddb1
Revises: 8d7896fa1125
Create Date: 2024-02-19 15:10:31.552708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041f91a5ddb1'
down_revision: Union[str, None] = '8d7896fa1125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
