"""rename table

Revision ID: 3699ba9459a4
Revises: 21aa4fab80b4
Create Date: 2024-02-11 09:37:52.558908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3699ba9459a4'
down_revision: Union[str, None] = '21aa4fab80b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sensor_value_type')
    op.add_column('sensor_log', sa.Column('entry_date', sa.Date(), nullable=False))
    op.add_column('sensor_log', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.drop_column('sensor_log', 'value_type_id')
    op.drop_column('sensor_log', 'creation_data')
    op.drop_column('sensor_log', 'sensor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_log', sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sensor_log', sa.Column('creation_data', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('sensor_log', sa.Column('value_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sensor_log', 'channel_id')
    op.drop_column('sensor_log', 'entry_date')
    op.create_table('sensor_value_type',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'sensor_id', name='sensor_value_type_pkey')
    )
    op.drop_table('sensor_channel')
    # ### end Alembic commands ###
