"""add is_log_value to SensorChannModel

Revision ID: 48549ded891f
Revises: ecbcb9f808e7
Create Date: 2024-02-20 09:02:28.355958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48549ded891f'
down_revision: Union[str, None] = 'ecbcb9f808e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_channel', sa.Column('is_log_value', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_channel', 'is_log_value')
    # ### end Alembic commands ###
