"""change entry_date in sensor_log to utc

Revision ID: 541263028ff0
Revises: 14e8ff08b3a5
Create Date: 2024-02-20 09:24:32.549383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541263028ff0'
down_revision: Union[str, None] = '14e8ff08b3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
