"""add foreignkey

Revision ID: 61b0c4f84979
Revises: 3699ba9459a4
Create Date: 2024-02-11 09:40:29.028165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b0c4f84979'
down_revision: Union[str, None] = '3699ba9459a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sensor_channel', 'sensor', ['sensor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sensor_log', 'sensor_channel', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_log', type_='foreignkey')
    op.drop_constraint(None, 'sensor_channel', type_='foreignkey')
    # ### end Alembic commands ###
