"""make ip unique

Revision ID: 8d7896fa1125
Revises: 3caa1ed9a960
Create Date: 2024-02-19 14:52:24.295320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7896fa1125'
down_revision: Union[str, None] = '3caa1ed9a960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sensor', ['ip_address'])
    op.create_unique_constraint(None, 'sensor', ['mac_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor', type_='unique')
    op.drop_constraint(None, 'sensor', type_='unique')
    # ### end Alembic commands ###
