"""add collection interval

Revision ID: c46fc8baa82b
Revises: a436ea809fc5
Create Date: 2024-02-19 15:50:33.729434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46fc8baa82b'
down_revision: Union[str, None] = 'a436ea809fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('collection_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'collection_interval')
    # ### end Alembic commands ###
