"""add collection interval not nullable

Revision ID: ecbcb9f808e7
Revises: c46fc8baa82b
Create Date: 2024-02-19 15:54:29.474629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbcb9f808e7'
down_revision: Union[str, None] = 'c46fc8baa82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor', 'collection_interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor', 'collection_interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
